PLACE_DETAILS = {
    "belagavi_fort": {
        "name": 'Belagavi Fort',
        "category": 'Fort',
        "history": 'Built in 1204 AD by the Ratta Dynasty, later ruled by the Adil Shahis and Marathas.',
        "architecture": 'Stone masonry with a deep surrounding moat and Persian inscriptions.',
        "famous_features": 'Ancient Mosques, Jain Temples, and the Ramakrishna Mission Ashram.',
        "lat": 15.859,
        "lon": 74.512,
        "best_time": 'Year-round',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Belagavi',
        "how_to_reach": 'Located in the heart of Belagavi city. You can take an auto-rickshaw from the CBT or Railway Station, which is barely 2 km away.',
        "local_tips": 'Carry drinking water. Photography is allowed but be respectful near the religious structures inside.',
        "detailed_history": "The Belagavi Fort is a towering chronicle of Indian history, its walls stained with the blood of multiple empires. Originally built with mud and stone in 1204 AD by the Ratta Dynasty, it was massively fortified by the Adil Shahi Sultans of Bijapur in the 16th century, who added the deep moat, massive bastions, and the majestic Safa Masjid. Later, it became a crucial military stronghold for the Maratha Empire, defending against Mughal expansions. In 1818, the British East India Company captured it, turning it into a military cantonment. During the Indian Independence movement, the fort served as a prison where Mahatma Gandhi was briefly incarcerated. Today, the coexistence of Jain Basadis and ancient Mosques inside its walls tells a profound story of Belagavi's syncretic cultural heritage.",
    },
    "bhimagad_wildlife_sanctury": {
        "name": 'Bhimagad Wildlife Sanctuary',
        "category": 'Wildlife',
        "history": 'Named after the Bhimagad Fort; famous for the bar-headed goose and tigers.',
        "architecture": 'Dense tropical forest and rugged Western Ghats terrain.',
        "famous_features": "Wroughton's free-tailed bat (critically endangered).",
        "lat": 15.57,
        "lon": 74.3,
        "best_time": 'October to March',
        "entry_fee": 'Rs. 50',
        "visit_duration": '4 Hours',
        "city": 'Khanapur',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "bird_sanctuary_gahatprabha": {
        "name": 'Ghataprabha Bird Sanctuary',
        "category": 'Wildlife',
        "history": 'Established around the Ghataprabha River stretch for migratory bird protection.',
        "architecture": 'Riverine forest and wetlands.',
        "famous_features": 'Demoiselle cranes and European storks.',
        "lat": 16.2167,
        "lon": 74.75,
        "best_time": 'November to February',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Gokak',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "chorla_ghat": {
        "name": 'Chorla Ghat',
        "category": 'Nature',
        "history": 'Strategic pass used historically for trade between Karnataka and Goa.',
        "architecture": 'Winding mountainous roads through Sahyadri range.',
        "famous_features": 'Lush green valley views and heavy mist during monsoon.',
        "lat": 15.6515,
        "lon": 74.1166,
        "best_time": 'Monsoon (July-Sept)',
        "entry_fee": 'Free',
        "visit_duration": '3 Hours',
        "city": 'Jamboti',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "godachimalaki_falls": {
        "name": 'Godchinamalaki Falls',
        "category": 'Waterfall',
        "history": 'A hidden natural wonder formed by the Markandeya river.',
        "architecture": 'Two-step cascading waterfall over rugged rock formations.',
        "famous_features": 'The quiet, serene environment away from crowds.',
        "lat": 16.1186,
        "lon": 74.8256,
        "best_time": 'August to October',
        "entry_fee": 'Free',
        "visit_duration": '3 Hours',
        "city": 'Gokak',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "gokak": {
        "name": 'Gokak Falls',
        "category": 'Waterfall',
        "history": "Known as the Niagara of India; site of Asia's first hydroelectric project.",
        "architecture": 'Red stone cliff plunge of 170 feet into a horseshoe-shaped valley.',
        "famous_features": '201-meter long suspension bridge over the river.',
        "lat": 16.1908,
        "lon": 74.8301,
        "best_time": 'July to October',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Gokak',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "hidkal_dam_hukkeri": {
        "name": 'Hidkal Dam',
        "category": 'Reservoir',
        "history": 'A major irrigation project built across the Ghataprabha river.',
        "architecture": 'Modern masonry and earthen dam structure.',
        "famous_features": 'Scenic sunset views and massive water reservoir.',
        "lat": 16.1523,
        "lon": 74.6512,
        "best_time": 'Post-Monsoon',
        "entry_fee": 'Free',
        "visit_duration": '1 Hour',
        "city": 'Hukkeri',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "jalavane_falls": {
        "name": 'Jalavane Falls',
        "category": 'Waterfall',
        "history": 'A local seasonal treasure located near the Karnataka-Goa border.',
        "architecture": 'Natural forest cascade dropping from basalt rocks.',
        "famous_features": 'Quiet forest atmosphere and trek-only access.',
        "lat": 15.6558,
        "lon": 74.3218,
        "best_time": 'July to September',
        "entry_fee": 'Free',
        "visit_duration": '4 Hours',
        "city": 'Khanapur',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "jamboti_falls": {
        "name": 'Jamboti Falls',
        "category": 'Waterfall',
        "history": 'A popular picnic spot originating in the Sahyadri mountains.',
        "architecture": 'Tumbling white water over green forest terrain.',
        "famous_features": 'Excellent photography spots and natural rock pools.',
        "lat": 15.6833,
        "lon": 74.3667,
        "best_time": 'August to December',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Jamboti',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "jamboti_hills": {
        "name": 'Jamboti Hills',
        "category": 'Nature',
        "history": 'A high-altitude forest region known as the source of Mandovi river.',
        "architecture": 'Evergreen forest hills with high rainfall records.',
        "famous_features": 'Mist-covered peaks and rich birdlife.',
        "lat": 15.7,
        "lon": 74.35,
        "best_time": 'Winter and Monsoon',
        "entry_fee": 'Free',
        "visit_duration": '3 Hours',
        "city": 'Belagavi',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "kamalbasadi_belagavi": {
        "name": 'Kamal Basadi',
        "category": 'Temple',
        "history": 'A 12th-century Jain temple built by the Ratta dynasty inside the fort.',
        "architecture": 'Famous for the 72-petal stone lotus carved on the ceiling.',
        "famous_features": 'Basalt stone pillars and Chalukyan carvings.',
        "lat": 15.8595,
        "lon": 74.5121,
        "best_time": 'Morning (8AM-11AM)',
        "entry_fee": 'Free',
        "visit_duration": '1 Hour',
        "city": 'Belagavi',
        "how_to_reach": 'Located inside the Belagavi Fort premises. Easily accessible by auto or taxi from anywhere in Belagavi city.',
        "local_tips": 'Best to visit early morning when the sunlight hits the intricate stone carvings. Photography is allowed but be respectful.',
        "detailed_history": 'Hidden within the massive walls of the Belagavi Fort lies the Kamal Basadi, a masterpiece of Jain mythology and architecture built in 1204 AD by Bichiraja, a minister of the Ratta Dynasty. The temple is famous for its breathtaking roof—a gigantic, intricately carved stone lotus (Kamal) featuring exactly 72 petals. In Jain cosmology, these 72 petals represent the 24 Tirthankaras (spiritual teachers) of the past, the 24 of the present, and the 24 of the future. The central idol is of Neminatha, the 22nd Tirthankara, carved out of pure black stone. This temple stands as a testament to the heavy Jain influence that shaped early Karnataka, surviving centuries of warfare and empire changes.',
    },
    "kapileshwar_temple_belagavi": {
        "name": 'Kapileshwar Temple',
        "category": 'Temple',
        "history": 'Considered the Dakshina Kashi; an ancient Shiva temple.',
        "architecture": 'Traditional North Karnataka Hindu temple style.',
        "famous_features": 'The sacred pushkarini (pond) and historic shivling.',
        "lat": 15.8435,
        "lon": 74.5032,
        "best_time": 'Mahashivratri festival',
        "entry_fee": 'Free',
        "visit_duration": '1 Hour',
        "city": 'Belagavi',
        "how_to_reach": 'Situated in Shahapur, Belagavi. It is located right in the city and can be easily reached by a short auto ride from the CBT.',
        "local_tips": 'It gets incredibly crowded during Mahashivratri and Shravan month. Visit on a regular weekday for a peaceful darshan.',
        "detailed_history": "Revered as 'Dakshina Kashi' (The Kashi of the South), Kapileshwar is arguably the most sacred spiritual center in Belagavi. According to ancient scriptures and local lore, the Shivling residing in the sanctum is 'Swayambhu' (self-manifested), meaning it was not carved by human hands but emerged naturally from the earth. The scriptures dictate that a pilgrimage to all the 12 Jyotirlingas spread across India remains spiritually incomplete until the devotee pours holy water over the Kapileshwar lingam. The temple complex is believed to have been an active site of worship for over a millennia, featuring a sacred Pushkarini (holy pond) where devotees take a cleansing dip during the grand Mahashivratri festival.",
    },
    "khanapur_forest": {
        "name": 'Khanapur Forest',
        "category": 'Forest',
        "history": 'A vast jungle corridor connecting the Western Ghats to the plains.',
        "architecture": 'Natural mix of moist deciduous and evergreen forest.',
        "famous_features": 'Great for road trips and landscape photography.',
        "lat": 15.6333,
        "lon": 74.5167,
        "best_time": 'September to January',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Khanapur',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "kittur_fort": {
        "name": 'Kittur Fort',
        "category": 'Fort',
        "history": 'Home of Rani Chennamma who fought British in 1824.',
        "architecture": 'Black basalt ruins with Peshwa-Islamic fusion.',
        "famous_features": 'Rani Chennamma Museum and the historic Durbar hall.',
        "lat": 15.6025,
        "lon": 74.7915,
        "best_time": 'October to March',
        "entry_fee": 'Rs. 20',
        "visit_duration": '2 Hours',
        "city": 'Kittur',
        "how_to_reach": 'Located around 50 km from Belagavi city on the Pune-Bengaluru Highway (NH4). State buses frequently ply to Kittur.',
        "local_tips": 'Visit the archaeological museum inside the fort premises which closes at 5 PM.',
        "detailed_history": "Kittur Fort is the legendary epicenter of early Indian resistance against the British Empire. Decades before the 1857 Mutiny, this basalt fort was ruled by the fierce Queen Rani Chennamma. In 1824, when the British East India Company attempted to annex Kittur using the 'Doctrine of Lapse,' Rani Chennamma famously declared war. Alongside her trusted general, Sangolli Rayanna, she commanded her forces from this very fort, inflicting a crushing defeat on the British forces in the first battle and killing the British collector St. John Thackeray. Though the British eventually returned with overwhelming artillery and captured the fort, its ruined durbar halls, water conduits, and shattered bastions remain a powerful monument to unmatched bravery and sacrifice.",
    },
    "kopeshwara_temple": {
        "name": 'Kopeshwara Temple',
        "category": 'Temple',
        "history": 'Ancient temple built by Shilahara Kings in the 12th century.',
        "architecture": 'Bhumija style with a circular open-to-sky hall.',
        "famous_features": 'Intricate stone elephant friezes at the temple base.',
        "lat": 16.6159,
        "lon": 74.6851,
        "best_time": 'Year-round',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Khidrapur',
        "how_to_reach": 'Located in Khidrapur, situated on the border of Maharashtra and Karnataka, roughly 85 km from Belagavi.',
        "local_tips": 'Look out for the stunning Swarga Mandap (open-to-sky hall) which is a masterpiece of ancient engineering.',
        "detailed_history": "The Kopeshwara Temple holds one of the most thrilling stories in Hindu mythology: the tale of the Daksha Yagna. Goddess Sati, unable to bear the public humiliation of her husband Lord Shiva by her arrogant father King Daksha, immolated herself in the sacrificial fire. When the news reached Mount Kailash, Lord Shiva fell into a universe-shattering, uncontrollable rage. He manifested as 'Kopeshwar' (The Angry God) and destroyed the Yagna. Lord Vishnu later managed to calm him down. Because Sati’s loyal mount, Nandi, had followed her to the yagna, he was not present when Shiva flew into his rage. This is the scriptural reason why Kopeshwara is one of the only ancient Shiva temples in India that does not have a Nandi statue facing the lingam! The temple's 'Swarga Mandap' (open-to-sky hall) was built by the Shilahara kings in the 12th century so the moon and sun could directly shine upon the angry lord to cool him.",
    },
    "kote_kere_belagavi": {
        "name": 'Kote Kere Lake',
        "category": 'Park',
        "history": 'A historic moat lake surrounding the Belagavi Fort.',
        "architecture": 'Developed recreational waterfront with paved tracks.',
        "famous_features": 'Musical fountain and floating docks.',
        "lat": 15.8592,
        "lon": 74.515,
        "best_time": 'Evening (6PM-8PM)',
        "entry_fee": 'Rs. 10',
        "visit_duration": '1 Hour',
        "city": 'Belagavi',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "military_mahadev_temple_belagavi": {
        "name": 'Military Mahadev Temple',
        "category": 'Temple',
        "history": 'Temple built and maintained by the Indian Army (MLIRC).',
        "architecture": 'Modern temple within lush military-maintained gardens.',
        "famous_features": 'Toy train and exceptionally clean environment.',
        "lat": 15.8321,
        "lon": 74.5212,
        "best_time": 'Any evening',
        "entry_fee": 'Free',
        "visit_duration": '1 Hour',
        "city": 'Belagavi',
        "how_to_reach": 'Located in the Camp area of Belagavi. It is easily reachable by city roads.',
        "local_tips": 'The temple complex includes a mini zoo and a toy train which is fantastic for children. Very clean and well-maintained.',
        "detailed_history": 'While not ancient in mythological terms, the Military Mahadev Temple carries immense patriotic and spiritual significance. It is operated by the Maratha Light Infantry Regimental Centre (MLIRC). The Maratha forces historically invoked Lord Shiva before marching into battle, echoing the war cries of Chhatrapati Shivaji Maharaj. This temple serves as the spiritual heart for the brave soldiers of the Indian Army stationed in Belagavi. The pristine, highly disciplined environment blends military precision with deep religious devotion, featuring beautiful gardens and a serene atmosphere meant to provide peace to off-duty soldiers.',
    },
    "navilutirtha_reservoir": {
        "name": 'Naviltirtha Reservoir',
        "category": 'Reservoir',
        "history": 'A scenic dam built in a narrow gorge in the hills.',
        "architecture": 'Engineering marvel with high rock cliffs on both sides.',
        "famous_features": 'A major peacock sanctuary in the surrounding hills.',
        "lat": 15.8124,
        "lon": 75.0912,
        "best_time": 'October to February',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Saundatti',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "parasgad_fort": {
        "name": 'Parasgad Fort',
        "category": 'Fort',
        "history": 'One of the oldest forts in the district (10th century).',
        "architecture": 'Built with irregular stone blocks without mortar.',
        "famous_features": 'View of the Yellamma Gudi temple from the fort peak.',
        "lat": 15.7678,
        "lon": 75.1128,
        "best_time": 'Winter mornings',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Saundatti',
        "how_to_reach": 'Located near Saundatti, roughly 85 km from Belagavi. You can hire a taxi from Saundatti town.',
        "local_tips": 'The trek to the top is rocky and uneven. Wear sturdy trekking shoes and carry a hat.',
        "detailed_history": 'Parasgad Fort is a rugged, ancient fortification dating back to the 10th century. Built upon a steep rocky outcrop near Saundatti, it is one of the oldest standing forts in the district. It was extensively used and later reinforced by Chhatrapati Shivaji Maharaj during his southern campaigns. The fort is a brilliant example of early defensive engineering, utilizing the natural sheer cliffs and massive irregular stone blocks assembled without mortar. The fort served a dual purpose: defending the rich Malaprabha river valley and guarding the sacred Yellamma Devi Temple located just across the gorge.',
    },
    "rakaskop_reservoir": {
        "name": 'Rakaskop Reservoir',
        "category": 'Reservoir',
        "history": 'Drinking water source for Belagavi; named after a giant.',
        "architecture": 'Masonry dam surrounded by peaceful forest hills.',
        "famous_features": 'The Rakshasa Cave located on the nearby hillside.',
        "lat": 15.8214,
        "lon": 74.4125,
        "best_time": 'Post-Monsoon',
        "entry_fee": 'Free',
        "visit_duration": '1 Hour',
        "city": 'Belagavi',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "ramdurga_fort": {
        "name": 'Ramdurga Fort',
        "category": 'Fort',
        "history": 'Administrative center for the Ramdurg Princely State.',
        "architecture": 'Classic Maratha hill fortification with bastions.',
        "famous_features": 'The scenic view of the Ramdurg valley below.',
        "lat": 15.945,
        "lon": 75.295,
        "best_time": 'October to February',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Ramdurg',
        "how_to_reach": 'Located in Ramdurg town, roughly 100 km from Belagavi. Regular buses connect Ramdurg to Belagavi.',
        "local_tips": 'The fort is massive; allocate at least 2 hours. Local guides are usually available near the entrance.',
        "detailed_history": 'The Ramdurga Fort stands as the proud administrative center of the erstwhile Ramdurg Princely State. Founded in the 18th century by the Bhave family, it functioned as a vital, non-salute Maratha stronghold during the turbulent years of the British Raj. The architecture is classic Maratha: thick, sloping stone walls designed to deflect cannon fire, large semicircular bastions, and hidden escape routes. The fort played a pivotal role in maintaining Maratha influence in the Karnataka region. Today, its massive iron-spiked gates and ruined palaces offer a nostalgic glimpse into the opulent, militarized lives of the Ramdurg rulers.',
    },
    "sada_falls": {
        "name": 'Sada Falls',
        "category": 'Waterfall',
        "history": 'A hidden gem near the Goa border requiring a trek.',
        "architecture": 'Natural 200m drop in the dense Sahyadri mountains.',
        "famous_features": 'Trek through streams and volcanic rock formations.',
        "lat": 15.6312,
        "lon": 74.2156,
        "best_time": 'July to November',
        "entry_fee": 'Free',
        "visit_duration": '5 Hours',
        "city": 'Chorla',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "siddheshwar_temple_belagavi": {
        "name": 'Siddheshwar Temple',
        "category": 'Temple',
        "history": 'A revered local temple dedicated to Lord Shiva.',
        "architecture": 'Traditional South Indian temple shikhara.',
        "famous_features": 'Peaceful meditation atmosphere and local festival fairs.',
        "lat": 15.845,
        "lon": 74.505,
        "best_time": 'Mondays and Shivratri',
        "entry_fee": 'Free',
        "visit_duration": '1 Hour',
        "city": 'Belagavi',
        "how_to_reach": 'Located in Kanabargi, Belagavi. Accessible via local auto or cab.',
        "local_tips": 'The temple is located near a hillock, offering a nice view and a cool breeze. Best visited in the late afternoon.',
        "detailed_history": "The Siddheshwar Temple is deeply embedded in the folk traditions of Belagavi. 'Siddheshwar' translates to 'The Lord who grants Siddhis' (perfections or boons). According to local Puranic beliefs, Lord Shiva resides here in a deeply meditative and benevolent state. Devotees believe that praying continuously for 40 Mondays at this shrine guarantees the fulfillment of one's deepest wishes. Surrounded by hills and nature, the temple acts as a spiritual anchor for the local community, especially during the vibrant Shravana month when the entire temple is draped in flowers and oil lamps.",
    },
    "surala_falls": {
        "name": 'Surala Falls',
        "category": 'Waterfall',
        "history": 'Also known as the Venezuela of Karnataka for its canyon.',
        "architecture": 'Powerful seasonal drop into a deep gorge.',
        "famous_features": 'Panoramic views from the Sural valley viewpoint.',
        "lat": 15.6667,
        "lon": 74.1667,
        "best_time": 'July to October',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Kankumbi',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "tilari_forest_belagavi": {
        "name": 'Tilari Forest',
        "category": 'Forest',
        "history": 'An important elephant corridor between Maharashtra and Karnataka.',
        "architecture": 'Steep ghat terrain and dense canopy forest.',
        "famous_features": 'Elephant sightings and the Tilari Ghat viewpoint.',
        "lat": 15.7598,
        "lon": 74.1213,
        "best_time": 'October to March',
        "entry_fee": 'Free',
        "visit_duration": '3 Hours',
        "city": 'Chandgad',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "vajrapoha_falls": {
        "name": 'Vajrapoha Falls',
        "category": 'Waterfall',
        "history": 'One of the highest falls in the district on Mandovi river.',
        "architecture": 'A majestic 200ft vertical drop over black rock cliffs.',
        "famous_features": 'Located deep in the jungle, requiring a local guide.',
        "lat": 15.6203,
        "lon": 74.3328,
        "best_time": 'September to November',
        "entry_fee": 'Free',
        "visit_duration": '5 Hours',
        "city": 'Khanapur',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "vidhansoudha_belagavi": {
        "name": 'Vidhana Soudha',
        "category": 'Heritage',
        "history": 'Administrative building built in 2012 for the second capital.',
        "architecture": 'Neo-Dravidian style inspired by the Bangalore building.',
        "famous_features": 'Grand central dome and massive stone pillars.',
        "lat": 15.8675,
        "lon": 74.5516,
        "best_time": 'Evening for the lights',
        "entry_fee": 'Free',
        "visit_duration": '1 Hour',
        "city": 'Belagavi',
        "how_to_reach": 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        "local_tips": 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        "detailed_history": 'This location holds significant local value in Belagavi district, known for its natural beauty and cultural heritage. It has been a popular local attraction for decades.',
    },
    "yellamadevi_temple_savandati": {
        "name": 'Yellamma Devi Temple',
        "category": 'Temple',
        "history": 'Major pilgrimage site for Goddess Renuka Yellamma.',
        "architecture": 'Built with Rashtrakuta and Chalukyan influences.',
        "famous_features": 'Annual Banada Hunnime and the Yellamma Gudi fair.',
        "lat": 15.7812,
        "lon": 75.1215,
        "best_time": 'November to February',
        "entry_fee": 'Free',
        "visit_duration": '3 Hours',
        "city": 'Saundatti',
        "how_to_reach": 'Located in Saundatti, about 80 km from Belagavi. Regular KSRTC buses run from Belagavi to Saundatti.',
        "local_tips": 'Avoid visiting during the massive Banada Hunnime festival unless you are prepared for extreme crowds.',
        "detailed_history": "The Yellamma Devi Temple, situated atop the scenic Yellammagudda hill in Saundatti, is the focal point of one of the most powerful and deeply worshipped Puranic legends in South India—the story of Goddess Renuka-Yellamma.\n\nAccording to the ancient scriptures, Princess Renuka married the fierce and powerful Sage Jamadagni. Her devotion and chastity towards her husband were so absolute that she acquired a divine Siddhi (supernatural power). Every morning, she would go to the Malaprabha River and fetch water using an unbaked, porous clay pot. The sheer strength of her purity held the unbaked mud together, allowing her to carry water without it dissolving.\n\nHowever, one fateful day, while fetching water, she noticed a Gandharva (a celestial king) named Chitraratha bathing in the river with his wives. For a fleeting fraction of a second, a thought of worldly desire crossed her mind. In that exact moment, her divine power vanished. The unbaked clay pot dissolved into the river, and she was forced to return to the ashram empty-handed and terrified.\n\nSage Jamadagni, utilizing his profound yogic vision, instantly realized what had transpired. Blinded by uncontrollable rage over her mental infidelity, he ordered his four elder sons to execute their mother. Horrified, they refused, and the sage immediately cursed them, turning them into stone. He then called upon his youngest son, Parashurama (who was an avatar of Lord Vishnu). Bound by absolute filial duty, Parashurama did not hesitate—he raised his axe and beheaded his mother.\n\nImmensely pleased by his son's unquestioning obedience, Jamadagni granted Parashurama a boon. Without missing a beat, Parashurama begged for his mother's life to be restored and for his brothers to be revived. Jamadagni agreed, handing Parashurama a pot of holy water and instructing him to attach the head to the body.\n\nIn his frantic rush to revive his mother, Parashurama made a cosmic error. He accidentally attached Renuka's head to the body of Matangi, a lower-caste woman who had been killed in the crossfire. When the holy water was sprinkled, the goddess awoke in a new, composite form: the head of a Brahmin queen and the body of a Dalit woman.\n\nThis miraculous resurrection transformed her into 'Yellamma'—which translates to 'Mother of All.' She transcended the rigid bounds of caste and became the supreme cosmic mother. Today, the temple stands as a monumental symbol of this unification. It draws millions of devotees from Karnataka, Maharashtra, and Goa, and is the spiritual center for the Devadasi community who worship her as the ultimate protector.",
    },
    "yellur_fort": {
        "name": 'Yellur Fort',
        "category": 'Fort',
        "history": 'Ancient hill fort also called Rajhansgad.',
        "architecture": 'High stone ramparts with watchtowers.',
        "famous_features": '360-degree sunset view over Belagavi city.',
        "lat": 15.7554,
        "lon": 74.5085,
        "best_time": 'Evening (4PM-6:30PM)',
        "entry_fee": 'Free',
        "visit_duration": '2 Hours',
        "city": 'Belagavi',
        "how_to_reach": 'Located roughly 15 km from Belagavi city. Best reached by private car or bike as the final stretch involves a steep hill climb.',
        "local_tips": 'Visit during the late afternoon. The sunset view from the top is breathtaking, but the road back down lacks streetlights.',
        "detailed_history": 'Towering over the Belagavi landscape on a high, isolated peak is the Yellur Fort, historically known as Rajhansgad. Believed to have been initially established by the Rashtrakutas, its strategic hilltop location made it highly coveted. It served as a prominent watchtower and defensive garrison for the Maratha Empire under the Peshwas to monitor enemy troop movements across the valley. The fort is renowned for an ancient, mysterious sweet-water well located at the very top of the hill—a geological anomaly that sustained besieged troops for months. Inside, an ancient Shiva temple continues to attract devotees, blending military history with spiritual reverence.',
    },
}
