PLACE_DETAILS = {
    'belagavi_fort': {
        'name': 'Belagavi Fort',
        'category': 'Fort',
        'history': 'Built in 1204 AD by the Ratta Dynasty, later ruled by the Adil Shahis and Marathas.',
        'architecture': 'Stone masonry with a deep surrounding moat and Persian inscriptions.',
        'famous_features': 'Ancient Mosques, Jain Temples, and the Ramakrishna Mission Ashram.',
        'lat': 15.859,
        'lon': 74.512,
        'best_time': 'Year-round',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Belagavi',
        'how_to_reach': 'Located in the heart of Belagavi city. You can take an auto-rickshaw from the CBT or Railway Station, which is barely 2 km away.',
        'local_tips': 'Carry drinking water. Photography is allowed but be respectful near the religious structures inside.',
        'detailed_history': "The Belagavi Fort is a towering chronicle of Indian history, its walls stained with the blood of multiple empires. Originally built with mud and stone in 1204 AD by the Ratta Dynasty, it was massively fortified by the Adil Shahi Sultans of Bijapur in the 16th century, who added the deep moat, massive bastions, and the majestic Safa Masjid. Later, it became a crucial military stronghold for the Maratha Empire, defending against Mughal expansions. In 1818, the British East India Company captured it, turning it into a military cantonment. During the Indian Independence movement, the fort served as a prison where Mahatma Gandhi was briefly incarcerated. Today, the coexistence of Jain Basadis and ancient Mosques inside its walls tells a profound story of Belagavi's syncretic cultural heritage.",
        'transport': {'distance_from_city': '2 km from Belagavi CBT', 'bus': [{'route': 'Belagavi CBT -> Fort Road', 'frequency': 'Every 15 mins', 'duration': '10 min', 'fare': '~Rs.10'}], 'auto_taxi': 'Auto from CBT: Rs.40-60. Taxi: Rs.150-200.', 'drive': 'Camp Road toward Fort Circle. Free parking at Fort gate.'},
    },
    'bhimagad_wildlife_sanctury': {
        'name': 'Bhimagad Wildlife Sanctuary',
        'category': 'Wildlife',
        'history': 'Named after the Bhimagad Fort; famous for the bar-headed goose and tigers.',
        'architecture': 'Dense tropical forest and rugged Western Ghats terrain.',
        'famous_features': "Wroughton's free-tailed bat (critically endangered).",
        'lat': 15.57,
        'lon': 74.3,
        'best_time': 'October to March',
        'entry_fee': 'Rs. 50',
        'visit_duration': '4 Hours',
        'city': 'Khanapur',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "Bhimagad Wildlife Sanctuary is one of Karnataka's most ecologically significant protected areas, nestled deep in the Western Ghats near Khanapur. The sanctuary takes its name from the ancient Bhimagad Fort, which crowns a rocky plateau within its borders — a ruin believed to have been a Maratha garrison used by Shivaji's generals. The sanctuary is most famous globally for being one of the last known roosting sites of the critically endangered Wroughton's free-tailed bat (Otomops wroughtoni), a species rediscovered here in 1999 after nearly 100 years of absence. The forest is part of a crucial wildlife corridor connecting the Dandeli-Anshi Tiger Reserve. Tigers, leopards, wild dogs (dholes), giant squirrels, and hornbills inhabit its dense canopy.",
        'transport': {'distance_from_city': '45 km via Khanapur', 'bus': [{'route': 'Belagavi CBT -> Khanapur', 'frequency': 'Every 45 mins', 'duration': '1 hr', 'fare': '~Rs.40'}, {'route': 'Khanapur -> Bhimagad (shared jeep)', 'frequency': 'On demand', 'duration': '30 min', 'fare': '~Rs.25-30'}], 'auto_taxi': 'Taxi from Belagavi: Rs.500-700 round trip.', 'drive': 'NH748 to Khanapur, then forest road. 4WD recommended.'},
    },
    'bird_sanctuary_gahatprabha': {
        'name': 'Ghataprabha Bird Sanctuary',
        'category': 'Wildlife',
        'history': 'Established around the Ghataprabha River stretch for migratory bird protection.',
        'architecture': 'Riverine forest and wetlands.',
        'famous_features': 'Demoiselle cranes and European storks.',
        'lat': 16.2167,
        'lon': 74.75,
        'best_time': 'November to February',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Gokak',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "The Ghataprabha Bird Sanctuary stretches along a 34-km stretch of the Ghataprabha River near Gokak, making it one of Karnataka's most rewarding birdwatching destinations. The river's shallow sandy banks and tall riparian vegetation attract hundreds of migratory species every winter. The sanctuary is particularly celebrated for the dramatic annual arrival of Demoiselle Cranes from Central Asia and European Storks from Scandinavia — a migration spectacle that has made it a landmark for ornithologists across India. The surrounding countryside is dotted with ancient Chalukyan temple ruins and sugarcane fields, which further enriches its landscape. Birdwatching seasons peak between November and February when the migratory visitors arrive in their thousands.",
        'transport': {'distance_from_city': '60 km near Gokak', 'bus': [{'route': 'Belagavi CBT -> Gokak', 'frequency': 'Every 30 mins', 'duration': '1.5 hrs', 'fare': '~Rs.60'}, {'route': 'Gokak -> Hidkal Junction', 'frequency': 'Every 1 hr', 'duration': '20 min', 'fare': '~Rs.20'}], 'auto_taxi': 'Auto from Gokak: Rs.150-200. Taxi from Belagavi: Rs.1200.', 'drive': 'NH67 to Gokak, then Ghataprabha River road.'},
    },
    'chorla_ghat': {
        'name': 'Chorla Ghat',
        'category': 'Nature',
        'history': 'Strategic pass used historically for trade between Karnataka and Goa.',
        'architecture': 'Winding mountainous roads through Sahyadri range.',
        'famous_features': 'Lush green valley views and heavy mist during monsoon.',
        'lat': 15.6515,
        'lon': 74.1166,
        'best_time': 'Monsoon (July-Sept)',
        'entry_fee': 'Free',
        'visit_duration': '3 Hours',
        'city': 'Jamboti',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "Chorla Ghat is a spectacular mountain pass snaking through the tri-junction of Karnataka, Goa, and Maharashtra at an elevation of roughly 750 metres above sea level. Historically, this ghat was a lifeline for trade caravans connecting the coastal ports of Goa with the Deccan Plateau, carrying spices, textiles, and salt. The Portuguese, who controlled Goa, used this route extensively during their colonial era. The pass cuts through the last surviving stretches of the Northern Western Ghats's semi-evergreen and moist deciduous forests. During monsoon, the entire range transforms into a cascading green paradise with hundreds of temporary waterfalls. The road itself is a favourite for motorcyclists and is considered one of the most scenic drives in peninsular India.",
        'transport': {'distance_from_city': '55 km (Goa border)', 'bus': [{'route': 'Belagavi CBT -> Jamboti', 'frequency': '3-4 buses/day', 'duration': '1.5 hrs', 'fare': '~Rs.55'}, {'route': 'Belagavi -> Panaji (Goa) via Chorla', 'frequency': '2 buses/day', 'duration': '4 hrs', 'fare': '~Rs.180'}], 'auto_taxi': 'Taxi from Belagavi: Rs.900-1100. Bike rentals recommended.', 'drive': 'SH20 toward Jamboti, then Chorla Ghat Road. Sharp hairpin bends - drive slowly.'},
    },
    'godachimalaki_falls': {
        'name': 'Godchinamalaki Falls',
        'category': 'Waterfall',
        'history': 'A hidden natural wonder formed by the Markandeya river.',
        'architecture': 'Two-step cascading waterfall over rugged rock formations.',
        'famous_features': 'The quiet, serene environment away from crowds.',
        'lat': 16.1186,
        'lon': 74.8256,
        'best_time': 'August to October',
        'entry_fee': 'Free',
        'visit_duration': '3 Hours',
        'city': 'Gokak',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': 'Godchinamalaki Falls is a pristine two-tiered waterfall formed by the Markandeya River as it descends from the Deccan Plateau near Gokak. Unlike the more commercialised falls in the district, Godchinamalaki remains largely off the beaten path. The falls are named after the nearby ancient Shiva temple dedicated to Godchinamalaki — a local form of Lord Shiva worshipped by the Veerashaiva community. The geological formation here is notable: the river cuts through volcanic basalt terraced in ancient lava flows, creating a dramatic natural amphitheatre. Local Jain literature from the Chalukyan era mentions this river as a sacred pilgrimage route, suggesting the valley has been a place of spiritual significance for over a thousand years.',
        'transport': {'distance_from_city': '65 km near Gokak', 'bus': [{'route': 'Belagavi CBT -> Gokak', 'frequency': 'Every 30 mins', 'duration': '1.5 hrs', 'fare': '~Rs.60'}, {'route': 'Gokak -> Godchinamalaki (shared auto)', 'frequency': 'On demand', 'duration': '30 min', 'fare': '~Rs.40'}], 'auto_taxi': 'Taxi from Belagavi: Rs.800-950 round trip.', 'drive': 'NH67 to Gokak, then village road to Yargatti. GPS: 16.1186N, 74.8256E.'},
    },
    'gokak': {
        'name': 'Gokak Falls',
        'category': 'Waterfall',
        'history': "Known as the Niagara of India; site of Asia's first hydroelectric project.",
        'architecture': 'Red stone cliff plunge of 170 feet into a horseshoe-shaped valley.',
        'famous_features': '201-meter long suspension bridge over the river.',
        'lat': 16.1908,
        'lon': 74.8301,
        'best_time': 'July to October',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Gokak',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "Gokak Falls is a thunderous 52-metre (170-foot) horseshoe-shaped plunge of the Ghataprabha River over red laterite cliffs — justly earning it the nickname 'The Niagara of India'. Its historical significance transcends its natural beauty: in 1887, Gokak became the site of Asia's first hydroelectric power project, built by the Jambu and Sons company to power the adjoining textile mill. The historic suspension bridge that spans the gorge, at 201 metres long, was constructed to give workers access to the powerhouse. The falls gained massive national attention in 1982 when actor and social activist Rajkumar led a landmark movement (the Gokak Agitation) demanding Kannada be granted official language status — making these falls the unlikely backdrop of a pivotal moment in Karnataka's linguistic identity.",
        'transport': {'distance_from_city': '60 km from Belagavi', 'bus': [{'route': 'Belagavi CBT -> Gokak', 'frequency': 'Every 30 mins', 'duration': '1.5 hrs', 'fare': '~Rs.60'}], 'auto_taxi': 'Auto from Gokak Bus Stand to falls: Rs.40-60. Taxi from Belagavi: Rs.700-850.', 'drive': 'NH67 to Gokak. Follow Gokak Falls signboards. Free parking at viewpoint.'},
    },
    'hidkal_dam_hukkeri': {
        'name': 'Hidkal Dam',
        'category': 'Reservoir',
        'history': 'A major irrigation project built across the Ghataprabha river.',
        'architecture': 'Modern masonry and earthen dam structure.',
        'famous_features': 'Scenic sunset views and massive water reservoir.',
        'lat': 16.1523,
        'lon': 74.6512,
        'best_time': 'Post-Monsoon',
        'entry_fee': 'Free',
        'visit_duration': '1 Hour',
        'city': 'Hukkeri',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': 'Hidkal Dam, built across the Ghataprabha River near Hukkeri, is one of the largest irrigation projects in Karnataka, serving the agriculturally rich northern Karnataka region. Constructed between 1977 and 1985, the dam has a gross storage capacity of 4.76 TMC and is a critical lifeline for the sugarcane and paddy farmers of Belagavi, Bagalkot, and Vijayapura districts. The dam site is flanked by picturesque rolling hills and is particularly stunning in the post-monsoon period when the reservoir fills to the brim and the spillway gates are opened. The area around the backwaters has become a popular viewpoint, especially at sunset when the water glows amber against the laterite hills. Fishing communities around the reservoir have lived here for generations, sustaining a unique culture tied to the river.',
        'transport': {'distance_from_city': '50 km (Hukkeri taluk)', 'bus': [{'route': 'Belagavi CBT -> Hukkeri', 'frequency': 'Every 1 hr', 'duration': '1 hr', 'fare': '~Rs.45'}, {'route': 'Hukkeri -> Hidkal Dam', 'frequency': '3 buses/day', 'duration': '25 min', 'fare': '~Rs.20'}], 'auto_taxi': 'Auto from Hukkeri: Rs.150-200. Taxi from Belagavi: Rs.650-800.', 'drive': 'SH51 to Hukkeri, then Hidkal Dam Road.'},
    },
    'jalavane_falls': {
        'name': 'Jalavane Falls',
        'category': 'Waterfall',
        'history': 'A local seasonal treasure located near the Karnataka-Goa border.',
        'architecture': 'Natural forest cascade dropping from basalt rocks.',
        'famous_features': 'Quiet forest atmosphere and trek-only access.',
        'lat': 15.6558,
        'lon': 74.3218,
        'best_time': 'July to September',
        'entry_fee': 'Free',
        'visit_duration': '4 Hours',
        'city': 'Khanapur',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': 'Jalavane Falls is a seasonal cascade hidden deep in the Mhadei Wildlife Corridor near the Karnataka-Goa border. The waterfall originates from a stream that eventually joins the Mhadei River, which is itself the subject of a decades-long inter-state water dispute between Karnataka, Goa, and Maharashtra. The trek to Jalavane passes through one of the most biodiverse forest belts of the Northern Western Ghats — a landscape of giant bamboo groves, wild pepper vines, and ancient teak trees. The forest trail is frequented by hornbills, malabar pied hornbills, and kingfisher species. The falls are only accessible during and after the monsoon season, making them a treasured seasonal pilgrimage for trekkers from Belagavi and Goa.',
        'transport': {'distance_from_city': '35 km via Khanapur', 'bus': [{'route': 'Belagavi CBT -> Khanapur', 'frequency': 'Every 45 mins', 'duration': '45 min', 'fare': '~Rs.35'}], 'auto_taxi': 'Auto from Khanapur: Rs.100-150. Taxi from Belagavi: Rs.580-700.', 'drive': 'NH748 to Khanapur, then forest trail. Bike preferred for last 5 km.'},
    },
    'jamboti_falls': {
        'name': 'Jamboti Falls',
        'category': 'Waterfall',
        'history': 'A popular picnic spot originating in the Sahyadri mountains.',
        'architecture': 'Tumbling white water over green forest terrain.',
        'famous_features': 'Excellent photography spots and natural rock pools.',
        'lat': 15.6833,
        'lon': 74.3667,
        'best_time': 'August to December',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Jamboti',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': 'Jamboti Falls tumbles through the Sahyadri mountains near the small village of Jamboti, a hamlet perched on the rim of the Deccan Plateau where the land plummets dramatically into the Konkan lowlands below. The area sits at an elevation where clouds literally pour through the gaps in the hills during monsoon, creating a surreal mist-drenched landscape. The falls feed into a natural pool surrounded by flat volcanic rock slabs — a spot beloved by local picnickers. Jamboti village itself has a fascinating colonial history: British officers stationed in Belagavi maintained hill bungalows here as summer retreats, enjoying the cooler temperatures and spectacular valley views. A few of these crumbling colonial-era structures still stand in the village.',
        'transport': {'distance_from_city': '50 km from Belagavi', 'bus': [{'route': 'Belagavi CBT -> Jamboti', 'frequency': '3-4 buses/day', 'duration': '1.5 hrs', 'fare': '~Rs.55'}], 'auto_taxi': 'Auto from Jamboti village: Rs.50-80. Taxi from Belagavi: Rs.700-850.', 'drive': 'SH20 toward Jamboti. Falls are a short walk from the village road.'},
    },
    'jamboti_hills': {
        'name': 'Jamboti Hills',
        'category': 'Nature',
        'history': 'A high-altitude forest region known as the source of Mandovi river.',
        'architecture': 'Evergreen forest hills with high rainfall records.',
        'famous_features': 'Mist-covered peaks and rich birdlife.',
        'lat': 15.7,
        'lon': 74.35,
        'best_time': 'Winter and Monsoon',
        'entry_fee': 'Free',
        'visit_duration': '3 Hours',
        'city': 'Belagavi',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "Jamboti Hills marks the highest rim of the Northern Western Ghats in the Belagavi district, forming the dramatic watershed between the Deccan Plateau and the Konkan coast. Geologically, this plateau edge is millions of years old, formed from Deccan Trappean volcanic basalt laid down by massive ancient lava flows. The hills are notably the origin point of the Mandovi River (Mahadayi), one of Goa's most sacred rivers, which originates as a small mountain stream here before descending through dense forest into the Konkan plains. The surrounding forests are among the wettest in Karnataka, receiving over 4,000mm of rainfall annually. This extraordinary rainfall nurtures endemic plant species, rare mosses, and a rich canopy that supports the endangered Lion-tailed Macaque and the Great Hornbill.",
        'transport': {'distance_from_city': '52 km from Belagavi', 'bus': [{'route': 'Belagavi CBT -> Jamboti', 'frequency': '3-4 buses/day', 'duration': '1.5 hrs', 'fare': '~Rs.55'}], 'auto_taxi': 'Taxi from Belagavi: Rs.700-900 round trip.', 'drive': 'SH20 via Kangrali to Jamboti Hills. Best by bike for flexibility.'},
    },
    'kamalbasadi_belagavi': {
        'name': 'Kamal Basadi',
        'category': 'Temple',
        'history': 'A 12th-century Jain temple built by the Ratta dynasty inside the fort.',
        'architecture': 'Famous for the 72-petal stone lotus carved on the ceiling.',
        'famous_features': 'Basalt stone pillars and Chalukyan carvings.',
        'lat': 15.8595,
        'lon': 74.5121,
        'best_time': 'Morning (8AM-11AM)',
        'entry_fee': 'Free',
        'visit_duration': '1 Hour',
        'city': 'Belagavi',
        'how_to_reach': 'Located inside the Belagavi Fort premises. Easily accessible by auto or taxi from anywhere in Belagavi city.',
        'local_tips': 'Best to visit early morning when the sunlight hits the intricate stone carvings. Photography is allowed but be respectful.',
        'detailed_history': 'Hidden within the massive walls of the Belagavi Fort lies the Kamal Basadi, a masterpiece of Jain mythology and architecture built in 1204 AD by Bichiraja, a minister of the Ratta Dynasty. The temple is famous for its breathtaking roof—a gigantic, intricately carved stone lotus (Kamal) featuring exactly 72 petals. In Jain cosmology, these 72 petals represent the 24 Tirthankaras (spiritual teachers) of the past, the 24 of the present, and the 24 of the future. The central idol is of Neminatha, the 22nd Tirthankara, carved out of pure black stone. This temple stands as a testament to the heavy Jain influence that shaped early Karnataka, surviving centuries of warfare and empire changes.',
        'transport': {'distance_from_city': '2 km (inside Belagavi Fort)', 'bus': [{'route': 'Belagavi CBT -> Fort Road', 'frequency': 'Every 15 mins', 'duration': '10 min', 'fare': '~Rs.10'}], 'auto_taxi': 'Auto from CBT: Rs.40-60. Walk from Fort gate: 5 minutes.', 'drive': 'Camp Road to Fort gate. Enter fort - temple is inside.'},
    },
    'kapileshwar_temple_belagavi': {
        'name': 'Kapileshwar Temple',
        'category': 'Temple',
        'history': 'Considered the Dakshina Kashi; an ancient Shiva temple.',
        'architecture': 'Traditional North Karnataka Hindu temple style.',
        'famous_features': 'The sacred pushkarini (pond) and historic shivling.',
        'lat': 15.8435,
        'lon': 74.5032,
        'best_time': 'Mahashivratri festival',
        'entry_fee': 'Free',
        'visit_duration': '1 Hour',
        'city': 'Belagavi',
        'how_to_reach': 'Situated in Shahapur, Belagavi. It is located right in the city and can be easily reached by a short auto ride from the CBT.',
        'local_tips': 'It gets incredibly crowded during Mahashivratri and Shravan month. Visit on a regular weekday for a peaceful darshan.',
        'detailed_history': "Revered as 'Dakshina Kashi' (The Kashi of the South), Kapileshwar is arguably the most sacred spiritual center in Belagavi. According to ancient scriptures and local lore, the Shivling residing in the sanctum is 'Swayambhu' (self-manifested), meaning it was not carved by human hands but emerged naturally from the earth. The scriptures dictate that a pilgrimage to all the 12 Jyotirlingas spread across India remains spiritually incomplete until the devotee pours holy water over the Kapileshwar lingam. The temple complex is believed to have been an active site of worship for over a millennia, featuring a sacred Pushkarini (holy pond) where devotees take a cleansing dip during the grand Mahashivratri festival.",
        'transport': {'distance_from_city': '4 km from Belagavi CBT', 'bus': [{'route': 'Belagavi CBT -> Shahapur', 'frequency': 'Every 20 mins', 'duration': '15 min', 'fare': '~Rs.12'}], 'auto_taxi': 'Auto from CBT: Rs.40-70.', 'drive': 'Khade Bazar Road to Shahapur. Temple signboard visible from road.'},
    },
    'khanapur_forest': {
        'name': 'Khanapur Forest',
        'category': 'Forest',
        'history': 'A vast jungle corridor connecting the Western Ghats to the plains.',
        'architecture': 'Natural mix of moist deciduous and evergreen forest.',
        'famous_features': 'Great for road trips and landscape photography.',
        'lat': 15.6333,
        'lon': 74.5167,
        'best_time': 'September to January',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Khanapur',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': 'Khanapur Forest is the southern fringe of the vast Dandeli-Anshi Tiger Reserve, making it part of one of the most significant tiger habitats in the Western Ghats. The forest is characterised by a mosaic of moist deciduous and semi-evergreen vegetation that transitions into riverine patches along the Malaprabha and its tributaries. The Khanapur-Jamboti road passes through the heart of this jungle, making it one of the most scenic forest drives in Karnataka. The forest corridors here are critical wildlife passages: elephants migrating between Maharashtra and Karnataka use these routes, and sightings of gaur (Indian bison), sambar deer, and leopards are not uncommon at dawn and dusk. A network of forest department fire-roads makes it an excellent terrain for guided jungle walks.',
        'transport': {'distance_from_city': '40 km from Belagavi', 'bus': [{'route': 'Belagavi CBT -> Khanapur', 'frequency': 'Every 45 mins', 'duration': '1 hr', 'fare': '~Rs.40'}], 'auto_taxi': 'Auto from Khanapur: Rs.150-200. Taxi from Belagavi: Rs.580-700.', 'drive': 'NH748 to Khanapur. Morning drive recommended for wildlife sightings.'},
    },
    'kittur_fort': {
        'name': 'Kittur Fort',
        'category': 'Fort',
        'history': 'Home of Rani Chennamma who fought British in 1824.',
        'architecture': 'Black basalt ruins with Peshwa-Islamic fusion.',
        'famous_features': 'Rani Chennamma Museum and the historic Durbar hall.',
        'lat': 15.6025,
        'lon': 74.7915,
        'best_time': 'October to March',
        'entry_fee': 'Rs. 20',
        'visit_duration': '2 Hours',
        'city': 'Kittur',
        'how_to_reach': 'Located around 50 km from Belagavi city on the Pune-Bengaluru Highway (NH4). State buses frequently ply to Kittur.',
        'local_tips': 'Visit the archaeological museum inside the fort premises which closes at 5 PM.',
        'detailed_history': "Kittur Fort is the legendary epicenter of early Indian resistance against the British Empire. Decades before the 1857 Mutiny, this basalt fort was ruled by the fierce Queen Rani Chennamma. In 1824, when the British East India Company attempted to annex Kittur using the 'Doctrine of Lapse,' Rani Chennamma famously declared war. Alongside her trusted general, Sangolli Rayanna, she commanded her forces from this very fort, inflicting a crushing defeat on the British forces in the first battle and killing the British collector St. John Thackeray. Though the British eventually returned with overwhelming artillery and captured the fort, its ruined durbar halls, water conduits, and shattered bastions remain a powerful monument to unmatched bravery and sacrifice.",
        'transport': {'distance_from_city': '50 km on NH4', 'bus': [{'route': 'Belagavi CBT -> Kittur (KSRTC)', 'frequency': 'Every 1 hr', 'duration': '1 hr 15 min', 'fare': '~Rs.55'}, {'route': 'Belagavi -> Dharwad (stops at Kittur)', 'frequency': 'Frequent', 'duration': '1 hr', 'fare': '~Rs.60'}], 'auto_taxi': 'Auto from Kittur Bus Stand to fort: Rs.30. Taxi from Belagavi: Rs.650-800.', 'drive': 'NH4 (Pune-Bengaluru Highway) to Kittur. Easy 50 km drive.'},
    },
    'kopeshwara_temple': {
        'name': 'Kopeshwara Temple',
        'category': 'Temple',
        'history': 'Ancient temple built by Shilahara Kings in the 12th century.',
        'architecture': 'Bhumija style with a circular open-to-sky hall.',
        'famous_features': 'Intricate stone elephant friezes at the temple base.',
        'lat': 16.6159,
        'lon': 74.6851,
        'best_time': 'Year-round',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Khidrapur',
        'how_to_reach': 'Located in Khidrapur, situated on the border of Maharashtra and Karnataka, roughly 85 km from Belagavi.',
        'local_tips': 'Look out for the stunning Swarga Mandap (open-to-sky hall) which is a masterpiece of ancient engineering.',
        'detailed_history': "The Kopeshwara Temple holds one of the most thrilling stories in Hindu mythology: the tale of the Daksha Yagna. Goddess Sati, unable to bear the public humiliation of her husband Lord Shiva by her arrogant father King Daksha, immolated herself in the sacrificial fire. When the news reached Mount Kailash, Lord Shiva fell into a universe-shattering, uncontrollable rage. He manifested as 'Kopeshwar' (The Angry God) and destroyed the Yagna. Lord Vishnu later managed to calm him down. Because Sati’s loyal mount, Nandi, had followed her to the yagna, he was not present when Shiva flew into his rage. This is the scriptural reason why Kopeshwara is one of the only ancient Shiva temples in India that does not have a Nandi statue facing the lingam! The temple's 'Swarga Mandap' (open-to-sky hall) was built by the Shilahara kings in the 12th century so the moon and sun could directly shine upon the angry lord to cool him.",
        'transport': {'distance_from_city': '85 km (Khidrapur, near Maharashtra border)', 'bus': [{'route': 'Belagavi CBT -> Nipani', 'frequency': 'Every 1 hr', 'duration': '2 hrs', 'fare': '~Rs.90'}, {'route': 'Nipani -> Khidrapur (local)', 'frequency': '3-4/day', 'duration': '45 min', 'fare': '~Rs.30'}], 'train': 'Belagavi Railway Station -> Kolhapur (1.5 hrs), then taxi ~Rs.600.', 'auto_taxi': 'Taxi from Belagavi: Rs.1100-1400 round trip.', 'drive': 'NH48 to Nipani, then Khidrapur Road.'},
    },
    'kote_kere_belagavi': {
        'name': 'Kote Kere Lake',
        'category': 'Park',
        'history': 'A historic moat lake surrounding the Belagavi Fort.',
        'architecture': 'Developed recreational waterfront with paved tracks.',
        'famous_features': 'Musical fountain and floating docks.',
        'lat': 15.8592,
        'lon': 74.515,
        'best_time': 'Evening (6PM-8PM)',
        'entry_fee': 'Rs. 10',
        'visit_duration': '1 Hour',
        'city': 'Belagavi',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "Kote Kere (Fort Lake) is the historic moat that encircles the Belagavi Fort. Originally excavated in the 12th century by the Ratta rulers as a critical defensive barrier, the moat served a dual purpose: it was a formidable obstacle for invading armies and a perennial water source for the fort's garrison. The Adil Shahis of Bijapur later deepened and widened it in the 16th century. After the British took over in 1818, they largely drained the military moat and later, in the post-independence era, it was developed into a recreational lake. Today, Kote Kere is a beautifully maintained urban oasis with a musical fountain, boating facilities, and a paved walking track. Evening visitors can see the fort walls and the old baobab trees (brought by African soldiers of the Adil Shahi army) reflected in the still water.",
        'transport': {'distance_from_city': '3 km from Belagavi CBT', 'bus': [{'route': 'Belagavi CBT -> Fort Circle', 'frequency': 'Every 15 mins', 'duration': '12 min', 'fare': '~Rs.10'}], 'auto_taxi': 'Auto from CBT: Rs.40-70. Evening fountain show at 7 PM.', 'drive': 'Camp Road to Fort Circle. Paid parking near lake entrance.'},
    },
    'military_mahadev_temple_belagavi': {
        'name': 'Military Mahadev Temple',
        'category': 'Temple',
        'history': 'Temple built and maintained by the Indian Army (MLIRC).',
        'architecture': 'Modern temple within lush military-maintained gardens.',
        'famous_features': 'Toy train and exceptionally clean environment.',
        'lat': 15.8321,
        'lon': 74.5212,
        'best_time': 'Any evening',
        'entry_fee': 'Free',
        'visit_duration': '1 Hour',
        'city': 'Belagavi',
        'how_to_reach': 'Located in the Camp area of Belagavi. It is easily reachable by city roads.',
        'local_tips': 'The temple complex includes a mini zoo and a toy train which is fantastic for children. Very clean and well-maintained.',
        'detailed_history': 'While not ancient in mythological terms, the Military Mahadev Temple carries immense patriotic and spiritual significance. It is operated by the Maratha Light Infantry Regimental Centre (MLIRC). The Maratha forces historically invoked Lord Shiva before marching into battle, echoing the war cries of Chhatrapati Shivaji Maharaj. This temple serves as the spiritual heart for the brave soldiers of the Indian Army stationed in Belagavi. The pristine, highly disciplined environment blends military precision with deep religious devotion, featuring beautiful gardens and a serene atmosphere meant to provide peace to off-duty soldiers.',
        'transport': {'distance_from_city': '5 km (Camp area)', 'bus': [{'route': 'Belagavi CBT -> MLIRC Gate', 'frequency': 'Every 30 mins', 'duration': '15 min', 'fare': '~Rs.15'}], 'auto_taxi': 'Auto from CBT: Rs.40-60.', 'drive': 'Khanapur Road to Cantonment Camp. Follow MLIRC signboard.'},
    },
    'navilutirtha_reservoir': {
        'name': 'Naviltirtha Reservoir',
        'category': 'Reservoir',
        'history': 'A scenic dam built in a narrow gorge in the hills.',
        'architecture': 'Engineering marvel with high rock cliffs on both sides.',
        'famous_features': 'A major peacock sanctuary in the surrounding hills.',
        'lat': 15.8124,
        'lon': 75.0912,
        'best_time': 'October to February',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Saundatti',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "Naviltirtha Reservoir, also known as Naviltirtha Dam, is an engineering marvel nestled in a spectacular narrow gorge where the Malaprabha River cuts through two towering vertical rock faces near Saundatti. The name 'Naviltirtha' translates to 'Peacock's Sacred Ford' in Kannada — a reflection of the spectacular population of Indian Peacocks that inhabit the surrounding hills. The dam was constructed primarily to provide drinking water to Saundatti and its surrounding villages. The gorge itself has a mythological dimension: local lore identifies this rocky chasm as the spot where the goddess Yellamma (Renuka Devi) descended from the Saundatti hill to bathe in the Malaprabha. The mirror-still reservoir surrounded by sheer cliffs and forest creates one of the most dramatic landscapes in North Karnataka.",
        'transport': {'distance_from_city': '80 km (Saundatti)', 'bus': [{'route': 'Belagavi CBT -> Saundatti', 'frequency': 'Every 1 hr', 'duration': '2 hrs', 'fare': '~Rs.90'}], 'auto_taxi': 'Auto from Saundatti to dam: Rs.80-100. Taxi from Belagavi: Rs.1600.', 'drive': 'NH67 to Gokak, then Saundatti Road. Dam viewpoint is well-signposted.'},
    },
    'parasgad_fort': {
        'name': 'Parasgad Fort',
        'category': 'Fort',
        'history': 'One of the oldest forts in the district (10th century).',
        'architecture': 'Built with irregular stone blocks without mortar.',
        'famous_features': 'View of the Yellamma Gudi temple from the fort peak.',
        'lat': 15.7678,
        'lon': 75.1128,
        'best_time': 'Winter mornings',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Saundatti',
        'how_to_reach': 'Located near Saundatti, roughly 85 km from Belagavi. You can hire a taxi from Saundatti town.',
        'local_tips': 'The trek to the top is rocky and uneven. Wear sturdy trekking shoes and carry a hat.',
        'detailed_history': 'Parasgad Fort is a rugged, ancient fortification dating back to the 10th century. Built upon a steep rocky outcrop near Saundatti, it is one of the oldest standing forts in the district. It was extensively used and later reinforced by Chhatrapati Shivaji Maharaj during his southern campaigns. The fort is a brilliant example of early defensive engineering, utilizing the natural sheer cliffs and massive irregular stone blocks assembled without mortar. The fort served a dual purpose: defending the rich Malaprabha river valley and guarding the sacred Yellamma Devi Temple located just across the gorge.',
        'transport': {'distance_from_city': '85 km (Saundatti)', 'bus': [{'route': 'Belagavi CBT -> Saundatti', 'frequency': 'Every 1 hr', 'duration': '2 hrs', 'fare': '~Rs.90'}], 'auto_taxi': 'Auto from Saundatti to fort base: Rs.80-120. Taxi from Belagavi: Rs.1600.', 'drive': 'NH67 to Gokak, Saundatti Road. Trek 30 min to fort top from base.'},
    },
    'rakaskop_reservoir': {
        'name': 'Rakaskop Reservoir',
        'category': 'Reservoir',
        'history': 'Drinking water source for Belagavi; named after a giant.',
        'architecture': 'Masonry dam surrounded by peaceful forest hills.',
        'famous_features': 'The Rakshasa Cave located on the nearby hillside.',
        'lat': 15.8214,
        'lon': 74.4125,
        'best_time': 'Post-Monsoon',
        'entry_fee': 'Free',
        'visit_duration': '1 Hour',
        'city': 'Belagavi',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "Rakaskop Reservoir, perched in the forested hills west of Belagavi city, serves as one of the primary drinking water sources for the district. Its name derives from the Kannada words 'Rakshasa' (giant demon) and 'Kop' (hill) — a local legend describes a giant who once resided in a cave on the adjacent hillside, which is still visible and visited by the curious. The masonry dam was constructed during the British colonial period to address the rapid growth of the military cantonment at Belagavi. The forested catchment around the reservoir is a protected area, and its relatively undisturbed state means that leopards, wild pigs, and a large variety of birds are regularly spotted near the waterline. The gentle hill surrounding the reservoir provides a peaceful circuit walk.",
        'transport': {'distance_from_city': '18 km from Belagavi CBT', 'bus': [{'route': 'Belagavi CBT -> Rakaskop (Khanapur Road)', 'frequency': '4-5/day', 'duration': '35 min', 'fare': '~Rs.25'}], 'auto_taxi': 'Auto from Belagavi: Rs.150-200. Taxi: Rs.500-600.', 'drive': 'NH748 west from Belagavi, take Rakaskop turnoff. Scenic forested approach.'},
    },
    'ramdurga_fort': {
        'name': 'Ramdurga Fort',
        'category': 'Fort',
        'history': 'Administrative center for the Ramdurg Princely State.',
        'architecture': 'Classic Maratha hill fortification with bastions.',
        'famous_features': 'The scenic view of the Ramdurg valley below.',
        'lat': 15.945,
        'lon': 75.295,
        'best_time': 'October to February',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Ramdurg',
        'how_to_reach': 'Located in Ramdurg town, roughly 100 km from Belagavi. Regular buses connect Ramdurg to Belagavi.',
        'local_tips': 'The fort is massive; allocate at least 2 hours. Local guides are usually available near the entrance.',
        'detailed_history': 'The Ramdurga Fort stands as the proud administrative center of the erstwhile Ramdurg Princely State. Founded in the 18th century by the Bhave family, it functioned as a vital, non-salute Maratha stronghold during the turbulent years of the British Raj. The architecture is classic Maratha: thick, sloping stone walls designed to deflect cannon fire, large semicircular bastions, and hidden escape routes. The fort played a pivotal role in maintaining Maratha influence in the Karnataka region. Today, its massive iron-spiked gates and ruined palaces offer a nostalgic glimpse into the opulent, militarized lives of the Ramdurg rulers.',
        'transport': {'distance_from_city': '100 km (Ramdurg town)', 'bus': [{'route': 'Belagavi CBT -> Ramdurg (KSRTC)', 'frequency': 'Every 2 hrs', 'duration': '2.5 hrs', 'fare': '~Rs.110'}], 'auto_taxi': 'Auto from Ramdurg to fort: Rs.30-50. Taxi from Belagavi: Rs.1300.', 'drive': 'NH67 to Gokak, then SH64 to Ramdurg. Fort on hilltop - visible from town.'},
    },
    'sada_falls': {
        'name': 'Sada Falls',
        'category': 'Waterfall',
        'history': 'A hidden gem near the Goa border requiring a trek.',
        'architecture': 'Natural 200m drop in the dense Sahyadri mountains.',
        'famous_features': 'Trek through streams and volcanic rock formations.',
        'lat': 15.6312,
        'lon': 74.2156,
        'best_time': 'July to November',
        'entry_fee': 'Free',
        'visit_duration': '5 Hours',
        'city': 'Chorla',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': 'Sada Falls is arguably the most dramatic and least-visited waterfall in the Belagavi district, plunging nearly 200 metres in a near-vertical drop over a sheer basalt cliff deep in the Sahyadri mountains near the Goa border. The falls are formed by a seasonal stream that carves through million-year-old volcanic rock before leaping into a dense jungle gorge far below. The approach to Sada Falls involves a challenging 5–6 km trek through dense forest, crossing multiple streams over volcanic stepping stones. The trail passes through landscapes of extraordinary geological beauty — ancient lava formations, orchid-laden trees, and crystalline forest pools. Due to its remoteness and seasonal nature, the falls remain a secret known primarily to serious trekkers and the local Kunbi tribal community who revere the gorge.',
        'transport': {'distance_from_city': '65 km (Chorla area)', 'bus': [{'route': 'Belagavi CBT -> Kankumbi / Chorla Junction', 'frequency': '2 buses/day', 'duration': '2 hrs', 'fare': '~Rs.70'}], 'auto_taxi': 'Taxi from Belagavi: Rs.1000-1200. Bike strongly recommended.', 'drive': 'SH20 to Chorla, then forest track. Bike/4WD only. Trek from Sada village.'},
    },
    'siddheshwar_temple_belagavi': {
        'name': 'Siddheshwar Temple',
        'category': 'Temple',
        'history': 'A revered local temple dedicated to Lord Shiva.',
        'architecture': 'Traditional South Indian temple shikhara.',
        'famous_features': 'Peaceful meditation atmosphere and local festival fairs.',
        'lat': 15.845,
        'lon': 74.505,
        'best_time': 'Mondays and Shivratri',
        'entry_fee': 'Free',
        'visit_duration': '1 Hour',
        'city': 'Belagavi',
        'how_to_reach': 'Located in Kanabargi, Belagavi. Accessible via local auto or cab.',
        'local_tips': 'The temple is located near a hillock, offering a nice view and a cool breeze. Best visited in the late afternoon.',
        'detailed_history': "The Siddheshwar Temple is deeply embedded in the folk traditions of Belagavi. 'Siddheshwar' translates to 'The Lord who grants Siddhis' (perfections or boons). According to local Puranic beliefs, Lord Shiva resides here in a deeply meditative and benevolent state. Devotees believe that praying continuously for 40 Mondays at this shrine guarantees the fulfillment of one's deepest wishes. Surrounded by hills and nature, the temple acts as a spiritual anchor for the local community, especially during the vibrant Shravana month when the entire temple is draped in flowers and oil lamps.",
        'transport': {'distance_from_city': '8 km from Belagavi CBT', 'bus': [{'route': 'Belagavi CBT -> Kanabargi', 'frequency': 'Every 30 mins', 'duration': '20 min', 'fare': '~Rs.15'}], 'auto_taxi': 'Auto from CBT: Rs.60-90.', 'drive': 'Khanapur Road to Kanabargi. Follow Siddheshwar Temple signboard.'},
    },
    'surala_falls': {
        'name': 'Surala Falls',
        'category': 'Waterfall',
        'history': 'Also known as the Venezuela of Karnataka for its canyon.',
        'architecture': 'Powerful seasonal drop into a deep gorge.',
        'famous_features': 'Panoramic views from the Sural valley viewpoint.',
        'lat': 15.6667,
        'lon': 74.1667,
        'best_time': 'July to October',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Kankumbi',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "Surala Falls — popularly called the 'Venezuela of Karnataka' — plunges into a spectacular flat-bottomed canyon eroded from basalt by the Sural River over millions of years. The canyon walls, which rise nearly 40 metres on both sides, have been sculpted into geometric hexagonal basalt columns by ancient volcanic cooling — a geological phenomenon similar to the famous Giant's Causeway in Ireland. The viewpoint at the canyon rim offers a panoramic sweep of the Sahyadri foothills merging into the Konkan lowlands. The river below the falls is crystal clear in winter and transforms into a powerful, roaring white torrent during monsoon. The unique canyon geology makes Surala Falls a site of significant scientific interest and it is frequently studied by geology students from Karnataka's universities.",
        'transport': {'distance_from_city': '65 km (Kankumbi)', 'bus': [{'route': 'Belagavi CBT -> Kankumbi', 'frequency': '2 buses/day', 'duration': '2 hrs', 'fare': '~Rs.75'}], 'auto_taxi': 'Taxi from Belagavi: Rs.950-1100 round trip.', 'drive': 'SH20 toward Chorla, then Sural Valley Road. Viewpoint parking available.'},
    },
    'tilari_forest_belagavi': {
        'name': 'Tilari Forest',
        'category': 'Forest',
        'history': 'An important elephant corridor between Maharashtra and Karnataka.',
        'architecture': 'Steep ghat terrain and dense canopy forest.',
        'famous_features': 'Elephant sightings and the Tilari Ghat viewpoint.',
        'lat': 15.7598,
        'lon': 74.1213,
        'best_time': 'October to March',
        'entry_fee': 'Free',
        'visit_duration': '3 Hours',
        'city': 'Chandgad',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': 'Tilari Forest occupies the dramatic Tilari Ghat section of the Sahyadri range in the Chandgad taluk of Belagavi district. This forest is a critical elephant corridor linking the forests of Amboli (Maharashtra) with the Dandeli-Anshi Tiger Reserve (Karnataka), making it one of the most important wildlife passage zones in the Western Ghats. Every year, herds of Indian elephants migrate through the Tilari valley following ancient seasonal routes. The forest is characterised by incredibly tall teak, rosewood, and Indian Kino trees with a dense canopy that barely lets light through. The Tilari River meanders through the valley below, cold and clear, fed by countless monsoon streams. The Chandgad-Goa highway passes through the heart of the forest, offering motorists unexpected elephant sightings.',
        'transport': {'distance_from_city': '75 km (Chandgad)', 'bus': [{'route': 'Belagavi CBT -> Chandgad', 'frequency': '3-4 buses/day', 'duration': '2.5 hrs', 'fare': '~Rs.100'}], 'auto_taxi': 'Taxi from Belagavi: Rs.1000-1300 round trip.', 'drive': 'NH48 toward Kolhapur, then Chandgad-Goa road. Elephant zone - drive slowly.'},
    },
    'vajrapoha_falls': {
        'name': 'Vajrapoha Falls',
        'category': 'Waterfall',
        'history': 'One of the highest falls in the district on Mandovi river.',
        'architecture': 'A majestic 200ft vertical drop over black rock cliffs.',
        'famous_features': 'Located deep in the jungle, requiring a local guide.',
        'lat': 15.6203,
        'lon': 74.3328,
        'best_time': 'September to November',
        'entry_fee': 'Free',
        'visit_duration': '5 Hours',
        'city': 'Khanapur',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "Vajrapoha Falls is a majestic, 60-metre (nearly 200-foot) cataract of the Mandovi (Mahadayi) River, cascading over jet-black basalt cliffs deep inside the Mhadei Wildlife Sanctuary near Khanapur. The name 'Vajrapoha' means 'Thunderbolt Strike' in Kannada — a name earned from the terrifying boom the falls produce during peak monsoon when the Mandovi runs in full force. The approach requires a full-day trek through dense jungle, navigating stream crossings, leech-infested paths, and rock scrambles. The falls are completely inaccessible from June to August when forest streams become impassable. In the dry season, an ancient underground cave system behind the falls becomes partially visible, and local tribal guides sometimes lead visitors inside. The surrounding jungle is a pristine undisturbed ecosystem with high biodiversity.",
        'transport': {'distance_from_city': '35 km (Khanapur forest)', 'bus': [{'route': 'Belagavi CBT -> Khanapur', 'frequency': 'Every 45 mins', 'duration': '45 min', 'fare': '~Rs.35'}], 'auto_taxi': 'Taxi from Belagavi: Rs.1000 to Khanapur base. Trek guide mandatory.', 'drive': 'NH748 to Khanapur. Falls trek starts from Vajrapoha forest check-post (6 km trail).'},
    },
    'vidhansoudha_belagavi': {
        'name': 'Vidhana Soudha',
        'category': 'Heritage',
        'history': 'Administrative building built in 2012 for the second capital.',
        'architecture': 'Neo-Dravidian style inspired by the Bangalore building.',
        'famous_features': 'Grand central dome and massive stone pillars.',
        'lat': 15.8675,
        'lon': 74.5516,
        'best_time': 'Evening for the lights',
        'entry_fee': 'Free',
        'visit_duration': '1 Hour',
        'city': 'Belagavi',
        'how_to_reach': 'Accessible by road from Belagavi. Private taxis or two-wheelers are recommended for convenience.',
        'local_tips': 'Check weather conditions before traveling, especially during the monsoon. Carry snacks as local stalls may be limited.',
        'detailed_history': "The Belagavi Vidhana Soudha is a neo-Dravidian masterpiece completed in 2012, serving as the second seat of Karnataka's legislative assembly — making Belagavi one of the very few cities in India to host a state legislature alongside the capital. The building was constructed as a statement of cultural pride and political recognition for the people of North Karnataka, who had long demanded greater administrative attention from Bengaluru. Designed by the PWD department, the building draws inspiration from its famous namesake in Bengaluru, featuring a central dome, imposing stone colonnades, and Karnataka state symbols carved in stone. The structure sits on expansive grounds and is most spectacular after dark when thousands of lights illuminate its facade and dome, making it visible from several kilometres away.",
        'transport': {'distance_from_city': '7 km from Belagavi CBT', 'bus': [{'route': 'Belagavi CBT -> Vidhana Soudha (NWKRTC)', 'frequency': 'Every 30 mins', 'duration': '20 min', 'fare': '~Rs.15'}], 'auto_taxi': 'Auto from CBT: Rs.100-150.', 'drive': 'Pune-Bengaluru Highway, take Cantonment exit. Soudha visible from highway.'},
    },
    'yellamadevi_temple_savandati': {
        'name': 'Yellamma Devi Temple',
        'category': 'Temple',
        'history': 'Major pilgrimage site for Goddess Renuka Yellamma.',
        'architecture': 'Built with Rashtrakuta and Chalukyan influences.',
        'famous_features': 'Annual Banada Hunnime and the Yellamma Gudi fair.',
        'lat': 15.7812,
        'lon': 75.1215,
        'best_time': 'November to February',
        'entry_fee': 'Free',
        'visit_duration': '3 Hours',
        'city': 'Saundatti',
        'how_to_reach': 'Located in Saundatti, about 80 km from Belagavi. Regular KSRTC buses run from Belagavi to Saundatti.',
        'local_tips': 'Avoid visiting during the massive Banada Hunnime festival unless you are prepared for extreme crowds.',
        'detailed_history': "The Yellamma Devi Temple, situated atop the scenic Yellammagudda hill in Saundatti, is the focal point of one of the most powerful and deeply worshipped Puranic legends in South India—the story of Goddess Renuka-Yellamma.\n\nAccording to the ancient scriptures, Princess Renuka married the fierce and powerful Sage Jamadagni. Her devotion and chastity towards her husband were so absolute that she acquired a divine Siddhi (supernatural power). Every morning, she would go to the Malaprabha River and fetch water using an unbaked, porous clay pot. The sheer strength of her purity held the unbaked mud together, allowing her to carry water without it dissolving.\n\nHowever, one fateful day, while fetching water, she noticed a Gandharva (a celestial king) named Chitraratha bathing in the river with his wives. For a fleeting fraction of a second, a thought of worldly desire crossed her mind. In that exact moment, her divine power vanished. The unbaked clay pot dissolved into the river, and she was forced to return to the ashram empty-handed and terrified.\n\nSage Jamadagni, utilizing his profound yogic vision, instantly realized what had transpired. Blinded by uncontrollable rage over her mental infidelity, he ordered his four elder sons to execute their mother. Horrified, they refused, and the sage immediately cursed them, turning them into stone. He then called upon his youngest son, Parashurama (who was an avatar of Lord Vishnu). Bound by absolute filial duty, Parashurama did not hesitate—he raised his axe and beheaded his mother.\n\nImmensely pleased by his son's unquestioning obedience, Jamadagni granted Parashurama a boon. Without missing a beat, Parashurama begged for his mother's life to be restored and for his brothers to be revived. Jamadagni agreed, handing Parashurama a pot of holy water and instructing him to attach the head to the body.\n\nIn his frantic rush to revive his mother, Parashurama made a cosmic error. He accidentally attached Renuka's head to the body of Matangi, a lower-caste woman who had been killed in the crossfire. When the holy water was sprinkled, the goddess awoke in a new, composite form: the head of a Brahmin queen and the body of a Dalit woman.\n\nThis miraculous resurrection transformed her into 'Yellamma'—which translates to 'Mother of All.' She transcended the rigid bounds of caste and became the supreme cosmic mother. Today, the temple stands as a monumental symbol of this unification. It draws millions of devotees from Karnataka, Maharashtra, and Goa, and is the spiritual center for the Devadasi community who worship her as the ultimate protector.",
        'transport': {'distance_from_city': '80 km (Saundatti)', 'bus': [{'route': 'Belagavi CBT -> Saundatti (KSRTC)', 'frequency': 'Every 1 hr', 'duration': '2 hrs', 'fare': '~Rs.90'}, {'route': 'Saundatti -> Yellamma Gudi (temple bus)', 'frequency': 'Every 30 mins', 'duration': '20 min', 'fare': '~Rs.15'}], 'auto_taxi': 'Auto from Saundatti: Rs.60-100. Taxi from Belagavi: Rs.1600.', 'drive': 'NH67 to Gokak, then Saundatti Road. Follow Yellamma Temple signboards.'},
    },
    'yellur_fort': {
        'name': 'Yellur Fort',
        'category': 'Fort',
        'history': 'Ancient hill fort also called Rajhansgad.',
        'architecture': 'High stone ramparts with watchtowers.',
        'famous_features': '360-degree sunset view over Belagavi city.',
        'lat': 15.7554,
        'lon': 74.5085,
        'best_time': 'Evening (4PM-6:30PM)',
        'entry_fee': 'Free',
        'visit_duration': '2 Hours',
        'city': 'Belagavi',
        'how_to_reach': 'Located roughly 15 km from Belagavi city. Best reached by private car or bike as the final stretch involves a steep hill climb.',
        'local_tips': 'Visit during the late afternoon. The sunset view from the top is breathtaking, but the road back down lacks streetlights.',
        'detailed_history': 'Towering over the Belagavi landscape on a high, isolated peak is the Yellur Fort, historically known as Rajhansgad. Believed to have been initially established by the Rashtrakutas, its strategic hilltop location made it highly coveted. It served as a prominent watchtower and defensive garrison for the Maratha Empire under the Peshwas to monitor enemy troop movements across the valley. The fort is renowned for an ancient, mysterious sweet-water well located at the very top of the hill—a geological anomaly that sustained besieged troops for months. Inside, an ancient Shiva temple continues to attract devotees, blending military history with spiritual reverence.',
        'transport': {'distance_from_city': '15 km from Belagavi CBT', 'bus': [{'route': 'Belagavi CBT -> Yellur village', 'frequency': '3-4 buses/day', 'duration': '35 min', 'fare': '~Rs.20'}], 'auto_taxi': 'Auto from Belagavi: Rs.150-200. Taxi: Rs.500-700.', 'drive': 'Hubli Road, left turn at Yellur signboard. Final 2 km is steep hill road.'},
    },
}
