"""
Pydantic schemas for the RAG chat endpoint.

Design:
- ChatRequest:  user message + optional conversation history
- DestinationRecommendation: LLM-generated 'reason' field + deterministic fields from DB
- ChatResponse: structured output — answer text + recommended destinations + source names

The LLM generates ONLY:
  - answer (free-form explanation text)
  - reason (why this place fits the query)

The LLM does NOT generate:
  - place_id, name, entry_fee, lat, lon, visit_duration (come from DB record)
  
This keeps deterministic data trustworthy and prevents hallucination of facts.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


class ChatMessage(BaseModel):
    """A single turn in the conversation history."""
    role: str = Field(description="'user' or 'assistant'")
    content: str


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=2000, description="User's question")
    history: List[ChatMessage] = Field(
        default_factory=list,
        max_length=10,
        description="Previous conversation turns (up to 10)",
    )

    @field_validator("message")
    @classmethod
    def message_must_not_be_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("message must not be empty or whitespace")
        return v.strip()


class DestinationRecommendation(BaseModel):
    """
    A destination recommended by the RAG assistant.
    
    - place_id / name / entry_fee / lat / lon: from database (deterministic)
    - reason: generated by LLM (explanation text — not factual claims)
    """
    place_id: int
    name: str
    category: Optional[str] = None
    city: Optional[str] = None
    entry_fee: Optional[str] = None
    visit_duration: Optional[str] = None
    best_time: Optional[str] = None
    folder_name: Optional[str] = None
    lat: Optional[float] = None
    lon: Optional[float] = None
    reason: str = Field(description="LLM-generated explanation why this place fits the query")


class ChatResponse(BaseModel):
    answer: str = Field(description="RAG-grounded answer to the user's question")
    destinations: List[DestinationRecommendation] = Field(
        description="Recommended destinations with deterministic metadata from DB"
    )
    sources: List[str] = Field(description="Names of retrieved destinations used as context")
    retrieved_count: int = Field(description="Number of documents retrieved from pgvector")
